### ISSUE TITLE
Running unsafe yields permission denied from the kernel

### ISSUE THREAD

**Issue by TheOnlyArtz** [redsift/redbpf#103]
I've followed the example of the http tracing and tweaked it a bit and finished up with:
```rs
#![no_std]
#![no_main]
use redbpf_macros::{map, program, xdp};
use redbpf_probes::bindings::*;
use redbpf_probes::net::Transport;
use redbpf_probes::xdp::prelude::*;

program!(0xFFFFFFFE, "GPL");

use hello_bpf::debug_http::RequestInfo;

#[map("requests")]
static mut requests: PerfMap<RequestInfo> = PerfMap::with_max_entries(1024);
// static mut requests: PerfMap<&str> = PerfMap::with_max_entries(1024);

#[xdp]
pub fn debug_http(ctx: XdpContext) -> XdpResult {
    let (ip, transport, data) = match (ctx.ip(), ctx.transport(), ctx.data()) {
        (Ok(ip), Ok(transport), Ok(data)) => (unsafe { *ip }, transport, data),
        _ => return Ok(XdpAction::Drop),
    };

    if let Ok(transport) = ctx.transport() {
        if transport.dest() == 80 {
            return Ok(XdpAction::Drop);
        }
    }

    let buff: [u8; 8] = match data.read() {
        Ok(b) => b,
        _ => return Ok(XdpAction::Pass),
    };
    let info = RequestInfo {
        saddr: ip.saddr,
        daddr: ip.daddr,
        sport: transport.source(),
        dport: transport.dest(),
    };

    unsafe {
        requests.insert(
            &ctx,
            &MapData::with_payload(info, data.offset() as u32, data.len() as u32),
        )
    };

    Ok(XdpAction::Pass)
}
```

I've found out that the code above can't be loaded because of the unsafe calls... this code for example, works just as fine:
```rs
#![no_std]
#![no_main]
use redbpf_macros::{map, program, xdp};
use redbpf_probes::bindings::*;
use redbpf_probes::net::Transport;
use redbpf_probes::xdp::prelude::*;

program!(0xFFFFFFFE, "GPL");

use hello_bpf::debug_http::RequestInfo;

#[map("requests")]
static mut requests: PerfMap<RequestInfo> = PerfMap::with_max_entries(1024);
#[xdp]
pub fn debug_http(ctx: XdpContext) -> XdpResult {

    if let Ok(transport) = ctx.transport() {
        if transport.dest() == 80 {
            return Ok(XdpAction::Drop);
        }
    }

    Ok(XdpAction::Pass)
}
```

When I'm trying to link the program to the kernel it outputs:
<details>
root@OpenWrt:~# ip link set eth1 xdp obj debug_http.elf sec xdp/debug_http

Prog section 'xdp/debug_http' rejected: Permission denied (13)!
 - Type:         6
 - Instructions: 93 (0 over limit)
 - License:      GPL

Verifier analysis:

Skipped 11782 bytes, use 'verb' option for the full verbose log.
[...]
value=60,var_off=(0x0; 0x3c)) R10=fp0
50: (2d) if r3 > r6 goto pc+41
 R0=inv1 R1=inv0 R2=pkt_end(id=0,off=0,imm=0) R3=pkt(id=0,off=0,r=34,imm=0) R4=pkt(id=1,off=14,r=0,umax_value=60,var_off=(0x0; 0x3c)) R5=inv1 R6=pkt(id=4,off=14,r=0,umax_value=60,var_off=(0x0; 0x3c)) R7=inv6 R8=inv(id=0,umax_value=60,var_off=(0x0; 0x3c)) R10=fp0
51: (bf) r7 = r6
52: (07) r7 += 20
53: (2d) if r7 > r2 goto pc+38
 R0=inv1 R1=inv0 R2=pkt_end(id=0,off=0,imm=0) R3=pkt(id=0,off=0,r=34,imm=0) R4=pkt(id=1,off=14,r=0,umax_value=60,var_off=(0x0; 0x3c)) R5=inv1 R6=pkt(id=4,off=14,r=34,umax_value=60,var_off=(0x0; 0x3c)) R7=pkt(id=4,off=34,r=34,umax_value=60,var_off=(0x0; 0x3c)) R8=inv(id=0,umax_value=60,var_off=(0x0; 0x3c)) R10=fp0
54: (71) r8 = *(u8 *)(r6 +12)
55: (bf) r6 = r8
56: (77) r6 >>= 2
57: (57) r6 &= 60
58: (07) r6 += 65516
59: (57) r6 &= 65532
60: (25) if r8 > 0x5f goto pc+1
 R0=inv1 R1=inv0 R2=pkt_end(id=0,off=0,imm=0) R3=pkt(id=0,off=0,r=34,imm=0) R4=pkt(id=1,off=14,r=0,umax_value=60,var_off=(0x0; 0x3c)) R5=inv1 R6=inv(id=0,umax_value=65532,var_off=(0x0; 0xfffc)) R7=pkt(id=4,off=34,r=34,umax_value=60,var_off=(0x0; 0x3c)) R8=inv(id=0,umax_value=95,var_off=(0x0; 0x7f)) R10=fp0
61: (b7) r6 = 0
62: (0f) r6 += r7
63: (b7) r7 = 1
64: (b7) r8 = 1
65: (2d) if r2 > r6 goto pc+1
 R0=inv1 R1=inv0 R2=pkt_end(id=0,off=0,imm=0) R3=pkt(id=0,off=0,r=34,imm=0) R4=pkt(id=1,off=14,r=0,umax_value=60,var_off=(0x0; 0x3c)) R5=inv1 R6=pkt(id=4,off=34,r=34,umax_value=60,var_off=(0x0; 0x3c)) R7=inv1 R8=inv1 R10=fp0
66: (b7) r8 = 0
67: (3d) if r6 >= r3 goto pc+13
 R0=inv1 R1=inv0 R2=pkt_end(id=0,off=0,imm=0) R3=pkt(id=0,off=0,r=34,imm=0) R4=pkt(id=1,off=14,r=0,umax_value=60,var_off=(0x0; 0x3c)) R5=inv1 R6=pkt(id=4,off=34,r=34,umax_value=60,var_off=(0x0; 0x3c)) R7=inv1 R8=inv0 R10=fp0
68: (b7) r7 = 0
69: (05) goto pc+11
81: (5f) r7 &= r8
82: (4f) r5 |= r1
83: (67) r5 <<= 32
84: (77) r5 >>= 32
85: (55) if r5 != 0x0 goto pc+6
 R0=inv1 R1=inv0 R2=pkt_end(id=0,off=0,imm=0) R3=pkt(id=0,off=0,r=34,imm=0) R4=pkt(id=1,off=14,r=0,umax_value=60,var_off=(0x0; 0x3c)) R5=inv0 R6=pkt(id=4,off=34,r=34,umax_value=60,var_off=(0x0; 0x3c)) R7=inv0 R8=inv0 R10=fp0
86: (57) r7 &= 1
87: safe

from 85 to 92: safe

from 67 to 81: R0=inv1 R1=inv0 R2=pkt_end(id=0,off=0,imm=0) R3=pkt(id=0,off=0,r=34,imm=0) R4=pkt(id=1,off=14,r=0,umax_value=60,var_off=(0x0; 0x3c)) R5=inv1 R6=pkt(id=4,off=34,r=34,umax_value=60,var_off=(0x0; 0x3c)) R7=inv1 R8=inv0 R10=fp0
81: (5f) r7 &= r8
82: (4f) r5 |= r1
83: (67) r5 <<= 32
84: (77) r5 >>= 32
85: safe

from 65 to 67: R0=inv1 R1=inv0 R2=pkt_end(id=0,off=0,imm=0) R3=pkt(id=0,off=0,r=34,imm=0) R4=pkt(id=1,off=14,r=0,umax_value=60,var_off=(0x0; 0x3c)) R5=inv1 R6=pkt(id=4,off=34,r=34,umax_value=60,var_off=(0x0; 0x3c)) R7=inv1 R8=inv1 R10=fp0
67: (3d) if r6 >= r3 goto pc+13
 R0=inv1 R1=inv0 R2=pkt_end(id=0,off=0,imm=0) R3=pkt(id=0,off=0,r=34,imm=0) R4=pkt(id=1,off=14,r=0,umax_value=60,var_off=(0x0; 0x3c)) R5=inv1 R6=pkt(id=4,off=34,r=34,umax_value=60,var_off=(0x0; 0x3c)) R7=inv1 R8=inv1 R10=fp0
68: (b7) r7 = 0
69: (05) goto pc+11
81: (5f) r7 &= r8
82: (4f) r5 |= r1
83: (67) r5 <<= 32
84: (77) r5 >>= 32
85: safe

from 67 to 81: R0=inv1 R1=inv0 R2=pkt_end(id=0,off=0,imm=0) R3=pkt(id=0,off=0,r=34,imm=0) R4=pkt(id=1,off=14,r=0,umax_value=60,var_off=(0x0; 0x3c)) R5=inv1 R6=pkt(id=4,off=34,r=34,umax_value=60,var_off=(0x0; 0x3c)) R7=inv1 R8=inv1 R10=fp0
81: (5f) r7 &= r8
82: (4f) r5 |= r1
83: (67) r5 <<= 32
84: (77) r5 >>= 32
85: (55) if r5 != 0x0 goto pc+6
 R0=inv1 R1=inv0 R2=pkt_end(id=0,off=0,imm=0) R3=pkt(id=0,off=0,r=34,imm=0) R4=pkt(id=1,off=14,r=0,umax_value=60,var_off=(0x0; 0x3c)) R5=inv0 R6=pkt(id=4,off=34,r=34,umax_value=60,var_off=(0x0; 0x3c)) R7=inv1 R8=inv1 R10=fp0
86: (57) r7 &= 1
87: (15) if r7 == 0x0 goto pc+4
 R0=inv1 R1=inv0 R2=pkt_end(id=0,off=0,imm=0) R3=pkt(id=0,off=0,r=34,imm=0) R4=pkt(id=1,off=14,r=0,umax_value=60,var_off=(0x0; 0x3c)) R5=inv0 R6=pkt(id=4,off=34,r=34,umax_value=60,var_off=(0x0; 0x3c)) R7=inv1 R8=inv1 R10=fp0
88: (69) r1 = *(u16 *)(r4 +2)
invalid access to packet, off=16 size=2, R4(id=1,off=14,r=0)
R4 offset is outside of the packet

Error fetching program/map!
</details>

**Comment by TheOnlyArtz** [comment]
Researching further more it seems like it's an issue with relocation of memory? looking at #84 didn't seem to help.
I would be glad to get some insight on this :]

**Comment by rsdy** [comment]
@TheOnlyArtz I can't test this immediately, but my guess is that you'll need to create a separate variable for `            MapData::with_payload(info, data.offset() as u32, data.len() as u32),` before passing it as a reference to `requests.insert`.

**Comment by TheOnlyArtz** [comment]
Hey, thanks for the replay, this did not work, unfortunately.
Here's a simplified version
```rs
#[map("requests")]
static mut requests: PerfMap<&str> = PerfMap::with_max_entries(1024);

#[xdp]
pub fn debug_http(ctx: XdpContext) -> XdpResult {
    if let Ok(transport) = ctx.transport() {
        if transport.dest() == 80 {
            return Ok(XdpAction::Drop);
        }
    }

    let data = MapData::with_payload("str", 0, 3);
    
    unsafe {
        requests.insert(
            &ctx,
            &data,
        )
    };

    Ok(XdpAction::Pass)
}
```
This didn't work, I've also tried to assign the arguments of the `with_payload` method to variables and same result.

**Comment by rsdy** [comment]
```
#![no_std]
#![no_main]
use cty::*;

// use one of the preludes
// use redbpf_probes::kprobe::prelude::*;
use redbpf_probes::maps::PerfMap;
use redbpf_probes::xdp::prelude::*;
// use redbpf_probes::socket_filter::prelude::*;

// Use the types you're going to share with userspace, eg:
// use test::test::SomeEvent;

program!(0xFFFFFFFE, "GPL");

struct Export {
    bytes: [u8; 3],
}

#[map("requests")]
static mut requests: PerfMap<Export> = PerfMap::with_max_entries(1024);

#[xdp("debug_http")]
pub fn debug_http(mut ctx: XdpContext) -> XdpResult {
    if let Ok(transport) = ctx.transport() {
        if transport.dest() == 80 {
            return Ok(XdpAction::Drop);
        }
    }

    let data = Export { bytes: *b"str" };

    unsafe { requests.insert(ctx.inner(), &data) };

    Ok(XdpAction::Pass)
}
```

This is an example that worked for me. The `PerfMap` in `redbpf_probes::xdp` is for exporting packet data, but that's not your intention here, so you'll need to use the generic `maps::PerfMap` interface. Additionally, raw strings are not supported because they generate an ELF section, so you'll need to use a byte array, and more specifically, I had to create a wrapper type for this to go through.

I hope this helps. Let me know if you have any other questions!

**Comment by TheOnlyArtz** [comment]
> ```
> #![no_std]
> #![no_main]
> use cty::*;
> 
> // use one of the preludes
> // use redbpf_probes::kprobe::prelude::*;
> use redbpf_probes::maps::PerfMap;
> use redbpf_probes::xdp::prelude::*;
> // use redbpf_probes::socket_filter::prelude::*;
> 
> // Use the types you're going to share with userspace, eg:
> // use test::test::SomeEvent;
> 
> program!(0xFFFFFFFE, "GPL");
> 
> struct Export {
>     bytes: [u8; 3],
> }
> 
> #[map("requests")]
> static mut requests: PerfMap<Export> = PerfMap::with_max_entries(1024);
> 
> #[xdp("debug_http")]
> pub fn debug_http(mut ctx: XdpContext) -> XdpResult {
>     if let Ok(transport) = ctx.transport() {
>         if transport.dest() == 80 {
>             return Ok(XdpAction::Drop);
>         }
>     }
> 
>     let data = Export { bytes: *b"str" };
> 
>     unsafe { requests.insert(ctx.inner(), &data) };
> 
>     Ok(XdpAction::Pass)
> }
> ```
> 
> This is an example that worked for me. The `PerfMap` in `redbpf_probes::xdp` is for exporting packet data, but that's not your intention here, so you'll need to use the generic `maps::PerfMap` interface. Additionally, raw strings are not supported because they generate an ELF section, so you'll need to use a byte array, and more specifically, I had to create a wrapper type for this to go through.
> 
> I hope this helps. Let me know if you have any other questions!

Woah! thank you :) it does work and it's amazing!

The only issue now is probably with Rust and OpenWRT's incompatibility with it's compiled when it comes to async operations (tokio ?) when running with a custom loader on OpenWRT the loop which reads the maps doesn't even run! but when trying to load the program on lets say an Ubuntu it runs just as fine. nothing which is related to RedBPF specifically but an interesting issue indeed.

**Comment by TheOnlyArtz** [comment]
Oh well, I do have a question @rsdy , how would I be able to pass the packet's data ( all of it ) to the user space? as the BCC needs fixed lengths it might not be possible? I wanted to know since we plan on implementing an IDS later on the project!

and btw, is there a Discord server / more convenient place we can chat in? I just feel like GH issues isn't the right place.

**Comment by rsdy** [comment]
@TheOnlyArtz I created a Matrix chatroom that you can join at https://app.element.io/#/room/!vCJcBZDeGUXaqSvPpL:rustch.at?via=rustch.at .

Passing the entire packet from the kernel to userspace is done exactly you tried the first time. This is precisely what happens in [ingraind](https://github.com/redsift/ingraind/blob/master/ingraind-probes/src/dns/main.rs#L34).

Currently waiting for a response in eBPF for a userland decision is a bit tricky. I believe Facebook has done some work on this, but it's not straightforward without working around eBPF limitations at the moment.
