### ISSUE TITLE
tc BPF programs only understand "maps" section

### ISSUE THREAD

**Issue by kbknapp** [redsift/redbpf#105]
BPF programs loaded by `tc` only understand  a single section called `maps`. The current [`map` macro](https://ingraind.org/api/redbpf_macros/attr.map.html) which places each map in its own `maps/<name>` section conflicts with how `tc` is used. To fix this one must manually rename the section with something like `llvm-objcopy --rename-section`, however this starts to fall over and become tedious when more than one map is required (you end up with multiple sections simply named `maps` which again confuses `tc`).

I'd be happy to submit a PR to either add a `tc_map` macro which places all defined maps into the same `maps` section, or alternatively add logic to the current macro and that if a map name is omitted (i.e. `#[map]`) its placed in the global `maps` section. I'd just need to know which route you would like to go, and if there are any other concerns to know about.

**Comment by alessandrod** [comment]
I think we should go for something like 

```rust
#[map(link_section = "maps")]
```

That's partly because `#[map]` used to have another meaning before I inadvertently broke it: 

```rust
#[map]
static FOO: u32 = 0;
```

used to be equivalent to:
 
```rust
#[map("FOO")]
static FOO: u32 = 0;
```

which was nice and ergonomic i think. Additionally having an explicit `link_section` attribute feels more future proof. I can imagine people wanting to use custom loaders with their own custom section names.

**Comment by alessandrod** [comment]
In fact I think we should probably deprecate `#[map("string literal")]` altogether, and just provide `link_section` for people that want the resulting ELF section be something other than `maps/item_name`

**Comment by kbknapp** [comment]
At the risk of getting into bike-shed territory, I'd recommend using `#[map(section = "foo")]` instead of `link_section` because most of the C I've run across uses either a `section` or `sec` macro for the same purpose...and it's shorter :smile: 

> for people that want the resulting ELF section be something other than maps/item_name

You mean going back to `#[map]` which would take on the `maps/item` name, but also providing a `#[map(link_section = "foo")]` to use explicit `foo` as the section, correct?

**Comment by alessandrod** [comment]
On Fri, 13 Nov 2020 at 1:39 pm, Kevin K. <notifications@github.com> wrote:

> At the risk of getting into bike-shed territory, I'd recommend using #[map(section
> = "foo")] instead of link_section because most of the C I've run across
> uses either a section or sec macro for the same purpose...and it's
> shorter 😄
>
> for people that want the resulting ELF section be something other than
> maps/item_name
>
> You mean going back to #[map] which would take on the maps/item name, but
> also providing a #[map(link_section = "foo")] to use explicit foo as the
> section, correct?
>

Yes correct. The reason I’d make it link_section is that rust already has
#[link_section] and it’s what the macro expands to.

**Comment by kbknapp** [comment]
I have a [working version in my fork](https://github.com/kbknapp/redbpf/blob/d27386e0dfd4b170fef45e1722159e06eb5aecb8/redbpf-macros/src/lib.rs#L153-L209), if you'd like me to make a PR just let me know. If you'd prefer to chew on it some more, or make some changes just let me know.

**Comment by alessandrod** [comment]
Great! Please do open a PR so we can discuss the code there
