### ISSUE TITLE
Is there a plan for supporting CO-RE?

### ISSUE THREAD

**Issue by rhdxmr** [redsift/redbpf#110]
Recently I heard of libbpf + CO-RE 😯
CO-RE seems to improve portability of BPF programs so that developers do not need to recompile BPF programs as kernel version of target host changes.
And some people predicts that BCC will be deprecated and libbpf + CO-RE will be de facto standard of BPF development.

I am wondering that redbpf has any plan for supporting CO-RE such as field-offset-relocation using BTF information.

**Comment by alessandrod** [comment]
It's the next big item on the todo list yes. The plan is to release 2.0 at some point in the next few months with support for BTF. There are some LLVM bugs to fix in order to get there which I'm planning to tackle soon.

**Comment by rhdxmr** [comment]
Thank you. I am looking forward to v2.0

**Comment by ZhangLei-cn** [comment]
Looking forward to this feature!
Maybe you can tell me the current progress? @alessandrod
