### ISSUE TITLE
LLVM_SYS_110_PREFIX

### ISSUE THREAD

**Issue by Dunateo** [redsift/redbpf#112]
Hello guys,
for a firewall project I need to use BPF and your library is really good but I am having trouble with the last version of rust and llvm 11. 
In the ubuntu dependencies you said llvm-10 but just on top llvm-11 which version to use ? 
And is it a problem of llvm or the crate is not up to date ?

`error: No suitable version of LLVM was found system-wide or pointed
       to by LLVM_SYS_110_PREFIX.

       Consider using `llvmenv` to compile an appropriate copy of LLVM, and
       refer to the llvm-sys documentation for more information.

       llvm-sys: https://crates.io/crates/llvm-sys
       llvmenv: https://crates.io/crates/llvmenv
   --> /Users/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/llvm-sys-110.0.0/src/lib.rs:486:1
    |
486 | / std::compile_error!(concat!(
487 | |     "No suitable version of LLVM was found system-wide or pointed
488 | |        to by LLVM_SYS_",
489 | |     env!("CARGO_PKG_VERSION_MAJOR"),
...   |
496 | |        llvmenv: https://crates.io/crates/llvmenv"
497 | | ));
    | |___^

error: aborting due to previous error

error: could not compile `llvm-sys`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-bpf v1.2.0`, intermediate artifacts can be found at `/var/folders/g9/l9j5rbks02b5xl_c03ykwm180000gn/T/cargo-installwKUd8e`

Caused by:
  build failed
`
thanks

**Comment by kbknapp** [comment]
You need LLVM 11 for the latest version of `redbpf`. The README is out of date, but there is a PR in to update it. 

Once you have LLVM 11 installed (you can confirm by running `llvm-config --version` which should return `11.0.0`), you'll just need to make sure your `LLVM_SYS_110_PREFIX` is set correctly if your install is not being detected automatically. `LLVM_SYS_110_PREFIX` should be pointing to your LLVM 11 install. For example on Fedora it would be `LLMV_SYS_110_PREFIX=/usr`, but I'm not sure what it is for your version of Ubuntu or where you've installed LLVM 11 to.

**Comment by alessandrod** [comment]
For the record setting the prefix won't be needed anymore once my fix here gets released https://gitlab.com/taricorp/llvm-sys.rs/-/merge_requests/8
