### ISSUE TITLE
"cargo install cargo-bpf" failing with LLVM_SYS_110_PREFIX error

### ISSUE THREAD

**Issue by sdbrain** [redsift/redbpf#113]
In an Ubuntu box after installing the dependencies as mentioned in README, `cargo install cargo-bpf` fails.

```
apt-get install -y curl \
	wget \
	gnupg2 \
	software-properties-common \
	build-essential \
	clang-10 \
	llvm-10 \
	libelf-dev \
	linux-headers-$(uname -r) \
	zlib1g \
	ca-certificates
```

I think this could be happening because of the recent update to use llvm11.

![image](https://user-images.githubusercontent.com/379818/100629111-8b8fe280-32ee-11eb-937b-2a6e0f6b34f9.png)

**Comment by sdbrain** [comment]
llvmenv also does not support 11.0.0 (`cargo install llvmenv`).. 11 is supported in the master branch of llvmenv though..

**Comment by alessandrod** [comment]
Oh yeah the top part of the README does mention LLVM 11, but then the bottom part still refers to LLVM 10. This needs to be fixed.

**Comment by sdbrain** [comment]
@alessandrod  Can you please let me know if you are using llvmenv or custom LLVM builds in your CI or dev env?

**Comment by alessandrod** [comment]
The README is outdated, you need llvm *11*. So that's the `llvm-11-dev` and `libclang-11-dev` packages. If you install those, either from your distro directly or from https://apt.llvm.org/, then it'll work.
