### ISSUE TITLE
docs on https://redsift.github.io/ appear out of date

### ISSUE THREAD

**Issue by ggriffiniii** [redsift/redbpf#19]
I am playing around with redbpf and the out of date rustdoc's are making it more challenging. I notice that docs.rs fails to build the crates, I'm assuming that's a known issue, but the docs on https://redsift.github.io/rust/redbpf/doc/redbpf_probes/xdp/struct.Data.html appear out of date. For example that page doesn't mention the read() method which appears to have been added last month.

**Comment by rsdy** [comment]
I forgot to tag the latest release on GitHub, as I published the crates locally. Should be fixed, thanks for spotting this.
