### ISSUE TITLE
`xdp::MapData` usage is unsound

### ISSUE THREAD

**Issue by HeroicKatora** [redsift/redbpf#23]
The definition and usage `MapData` not only allows arbitrary memory leaks and any usage that has non-zero `size` or `offset` *will*¹ trigger it internally. `MapData` is defined as thus:

```rust
pub struct MapData<T> {
    /// The custom data type to be exchanged with user space.
    pub data: T,
    offset: u32,
    size: u32,
    payload: [u8; 0],
}
```

There is one positive thing to note: The author was aware that exposing the `size` and `offset` publicly would lead to undesired behaviour as these are later used in the `payload` method.

```rust
    pub fn payload(&self) -> &[u8] {
        unsafe {
            let base = self.payload.as_ptr().add(self.offset as usize);
            slice::from_raw_parts(base, (self.size - self.offset) as usize)
        }
    }
```

The first issue, though: There exists a safe constructor for `MapData` which is allowed to specify *any* offset and size. Even such as `size < offset` which will lead to an obviously too-long slice.

However, the usage is even more worrying. There is *no* public way to correct construct a `MapData` that has any payload. It is expected as a **value** parameter to `PerfMap::insert_with_flags`. This will firstly also trust the `size` and secondly within that method any effort that could have made the payload previously valid has become moot. The argument value can be moved around while making the call and so it no longer guarantees that it is part of any allocation that actually contains the payload. **This code will at some point expose data from the stack.**

This whole code is reminiscient of a gcc-extension enabled C-style code base that contained a struct like:
```c
struct MapData {
    __u32 offset,
    __u32 size,
    char payload [0],
};
```

The correct transliteration is a dynamically sized struct:
```rust
#[repr(C)]
pub struct MapData<T> {
    /// The custom data type to be exchanged with user space.
    pub data: T,
    offset: u32,
    size: u32,
    payload: [u8], // A slice is also a type, just not a Sized one.
}
```

It becomes more complicated to actually get values of such an unsized type but that's where `unsafe` **but `sound`** wrappers are supposed to be used. How do you work with these structs you ask? Behind references, mostly. Creating them by value is not (yet) possible² but you can use references to them as normal parameters. For example:

```rust
impl<T> MapData<T> {
    pub fn offset&self) -> u32 {
        self.offset
    }
}
```

Creating requires some a few bits of manual code but the following would allocate a simple Box that contains no payload. This is also sound according to the documentation of [`Box::from_raw`](https://doc.rust-lang.org/stable/std/boxed/struct.Box.html#method.from_raw) and [the module](https://doc.rust-lang.org/stable/std/boxed/index.html#memory-layout). The hard parts are a) unsizing the type within the `Box` which requires a generic helper type; b) generalize this result.

```rust
impl<T> From<T> for Box<MapData<T>> {
pub fn new(data: T) -> Box<Self> {
        struct MapDataWithUnsizablePayload<T, U: ?Sized> {
            data: T, 
            offset: u32, 
            size: u32,
            payload: U,
        }
        
        let boxed = Box::new(MapDataWithUnsizablePayload::<T, [u8; 0]> {
            data,
            offset: 0,
            size: 0,
            payload: [],
        });
        
        let unsize: Box<MapDataWithUnsizablePayload<T, [u8]>> = boxed;
        unsafe {
            /// SAFETY: Those two structs are the same and have specified layout.
            Box::from_raw(Box::into_raw(unsize) as *mut MapData<T>)
        }
    }
}
```

-------------

¹ If you've not observed this then the calling convention of your compilation target likely save you. Since the struct is rather large, it is likely passed by-pointer in almost every case. Then, by sheer luck, the initial 'allocation on the stack still has the same address which is the argument to `bpf_perf_event_output` in the end — which is [here](https://github.com/redsift/redbpf/blob/5c1eff36279af19b6a7c9a43227e16e3b8234a86/redbpf-probes/src/maps.rs#L187-L196).

```rust
    pub fn insert_with_flags<C>(&mut self, ctx: *mut C, mut data: T, flags: PerfMapFlags) {
        unsafe {
            bpf_perf_event_output(
                ctx as *mut _ as *mut c_void,
                &mut self.def as *mut _ as *mut c_void,
                flags.into(),
                // HERE: if we are lucky, the calling convention makes this a pointer conversion.
                // Instead of taking the address of some arbitrary stack-local of this value.
                &mut data as *mut _ as *mut c_void,
                mem::size_of::<T>() as u64,
            );
        };
    }
```

² This does not mean abandoning the notion of having a payload. Convert all arguments taking a `MapData` to instead take a mutable reference to one. Then *the caller* can be obligated to make a fitting allocation. This would also fit with the two following methods:

```rust
use std::mem::{align_of, size_of};
use std::alloc::Layout;
use std::convert::TryFrom;

impl<T> MapData<T> {
    /// Calculate the layout of a value with some payload bytes.
    pub fn layout_with_payload(payload_len: u32) -> Option<Layout> {
        let payload_len: usize = usize::try_from(payload_len).ok()?;
        // Note: may want to switch to safe API once exposed (#55724).
        let base_size = size_of::<T>();
        let align = align_of::<T>().max(align_of::<u32>());
        let size_at_offset = base_size + base_size.wrapping_neg()%4;
        let size = size_at_offset + 2*size_of::<u32>() + payload_len;
        Layout::from_size_align(size, align).ok()
    }

    /// Declare a payload following the MapData.
    /// # Safety
    /// Caller has to guarantee that there is an actual allocation of `size` bytes that 
    /// is not currently pointed-to and alive for the same lifetime as the `MapData`.
    pub unsafe fn resize(&mut self, offset: u32, size: u32) {
        self.offset = offset;
        self.size = size;
    }
}
```

**Comment by rsdy** [comment]
Related to #20 .

**Comment by HeroicKatora** [comment]
Yes, I just wanted to extract from the thread to give the direct fix proposals and to provide a separate PR if possible. Since the crate is `no_std` we can obviously not do the `new() -> Box<MapData<T>>` but it should nevertheless be possible to do the rest of the fixes. How many depends on the scope of the rework of `MapData`. If one were to define `MapData` as the `MapDataWithUnsizablePayload` then it would still be possible to construct a sized value on the stack and then give a mutable reference to that to the other methods.

**Comment by HeroicKatora** [comment]
So two basic options:
* Redefine `MapData<T>` as that and change the insertion method:
  ```rust
  struct MapData<T, U: ?Sized> {
      data: T, 
      offset: u32, 
      size: u32,
      payload: U,
  }
  impl<T> PerfMap<T> {
      fn insert(&mut self, ctx: &XdpContext, data: &mut MapData<T, [u8]>);
  }
  ```
  This has the advantage of interaction with the type system and permitting nice on-stack construction of arbitrary payload types by letting the user choose for example any `U = [u8; N]`. Additionally, I think that most of the code can be completely safe.
* Do not change the definition to include a second type parameter but instead add a new definition for a layout-compatible struct that does not include a payload. Add a conversion method that converts a reference to the latter to a reference to the former. This needs less intrusive changes to the type itself but requires some manual `unsafe` conversion and possibly checks.

**Comment by rsdy** [comment]
We have a few ideas to making kernel-space code and user-space code better separated on the crate level.

Without fully going into details, in eBPF-land soundness issues don't work like they do in the userspace, and a lot of stuff we're doing is counter-intuitively sound. There are a few soundness issues raised in the other thread that we will work to address as part of this cleanup. At the same time, some "cleanups" are straight up not possible because of the peculiarities of the eBPF VM and runtime, and the way memory works inside the VM.

When we get to this, we will go through our existing interfaces, and take these comments on board in the best way possible.

**Comment by ssokolow** [comment]
By definition, if it's unsound at the Rust level, that means you may be invoking undefined behaviour and, if you invoke undefined behaviour, it doesn't matter what the eBPF VM does, because it can't magically undo unwanted transformations performed by the LLVM optimizers.

**Comment by HeroicKatora** [comment]
Due to the examples above not being very illustrative, the compiler might decide it's better to replace a path that calls `insert` with a non-zero payload with a call to `exit`. Or to, from that point onwards, dump available memory into random other places in memory (e.g. your loaded crypto keys into a data packet). And then you get roughly what happend in Heartbleed. Yes, code running in eBPF VM can not affect the kernel *integrity* but to get anywhere close to a reasonable dataflow analysis within the eBPF running code you *will* need to not perform UB.

> At the same time, some "cleanups" are straight up not possible because of the peculiarities of the eBPF VM and runtime, and the way memory works inside the VM.

Since llvm can compile to these systems, I find it highly unlikely that it could not be written in *sound* code. I might believe that some parts are hard to write in safe code but soundness should not be a blocker, except as a blocker for release.

**Comment by alessandrod** [comment]
I had somehow missed this. @HeroicKatora please read https://github.com/redsift/redbpf/issues/20#issuecomment-568390531, it explains how MapData is meant to work.

MapData is a thin abstraction over the way the kernel attaches XDP data to perf events. Please take a look at how that works.

**Comment by HeroicKatora** [comment]
The patch looks good to me, as far as `MapData` is concerned. What is now exposed in `redbpf-probes` seem sound according to Rust's memory model :+1: Also, the interface now follows the functionality more closely and I find it less confusing.

The ported part in `redbpf` seems better since it at least encapsulates all operations. However, I'm not completely convinced about its *soundness*. As far as I understood, this part will also not be executed in the bpfVM so any arguments of ignoring soundness will not be applicable. The `payload` still creates a reference to regions outside the original `&Sample` reference. Note that can not be said to be strictly UB-free *even if the allocation behind it is large enough*.¹ I think it is likely that one can rework `Sample` and `MapData` to an unsized type and fix this soundness problem.

-----

This is not yet defined to be UB either. It just has not been defined yet. [Some discussion on pointer provenance here](https://github.com/rust-lang/unsafe-code-guidelines/issues/52). Pointer provenance means that a raw pointer created from a reference may only be used to access the parts of memory to which the original reference pointed. The `payload` function in particular creates a pointer from the `&self` reference and thus *is very likely* only valid for the short header and not any of its tail.
