### ISSUE TITLE
bpf-sys macOS fails to compile due to usage of non-existent field (utsname->domainname) 

### ISSUE THREAD

**Issue by aviramha** [redsift/redbpf#34]
Probably will fail for other BSD platforms.
I'll try to submit a PR soon :)

**Comment by rsdy** [comment]
Since eBPF is Linux-only, I'm not entirely certain about the usecase here.

**Comment by aviramha** [comment]
bpf-sys could be useful for BPFs on macOS also

**Comment by rsdy** [comment]
bpf-sys has a direct dependency on the libraries lifted from the [Linux tree](https://github.com/redsift/libbpf/tree/4d86cae4f09f3db67d6d0543f94546f85f7b2c38)

If you would like to explore a BSD-aware bpf-sys, I'm more than happy to merge that patch, but I'm afraid it might be a large undertaking.
