### ISSUE TITLE
Should items in redbpf_probes::xdp::MapData be public?

### ISSUE THREAD

**Issue by rtkaratekid** [redsift/redbpf#42]
Going through the source code and whatever examples I can find and building what I can right now. Going through an example from [this blog](https://blog.redsift.com/labs/writing-bpf-code-in-rust/) about how to write a use-space elf loader and came across two issues. I recognize that this could been seen as an "unofficial" example, so I'm not sure how relevant the issues really are.

First compiler issue:
```sh
error[E0616]: field `data` of struct `redbpf_probes::xdp::MapData` is private
  --> src/main.rs:32:29
   |
32 |                 let info = &event.data;
   |                             ^^^^^^^^^^
```
is thrown when calling:
```rust
for event in events {
                let event = unsafe { &*(event.as_ptr() as *const MapData<RequestInfo>) };
                let info = &event.data;
``` 
Should these fields be marked public in `MapData`?

Second seems more like an API change that I haven't dug much into yet, but maybe it was either overlooked or I should just be looking to Ingraind for examples?

```sh
error[E0599]: no method named `payload` found for type `&redbpf_probes::xdp::MapData<bpf_examples::trace_http::RequestInfo>` in the current scope
  --> src/main.rs:33:61
   |
33 |                 let payload = String::from_utf8_lossy(event.payload());
   |                                                             ^^^^^^^ private field, not a method
```

When calling
```rust
let payload = String::from_utf8_lossy(event.payload());
```
on the event variable from above.

Let me know if these issues are helpful as I continue poking around the code. I think what I've seen so far I've really enjoyed!

**Comment by rsdy** [comment]
Thanks, this is very actually helpful!

The short answer is that the API has changed.

The long answer here is that for the next week or so the API is in flux, and the code in the blogpost is now obsolete. We're focusing on pulling the documentation together for writing probes, and we should be in a much better place in a few weeks.

For now, it's probably best if you look at the ingraind codebase for [XDP](https://github.com/redsift/ingraind/blob/master/ingraind-probes/src/dns/main.rs) examples. The [userspace](https://github.com/redsift/ingraind/blob/master/src/grains/dns.rs) side of things has also changed slightly.

After we tag 1.0, we'll start following semver, so confusion like this won't come up. I'll also put some independent XDP examples in the repo that we'll build as part of the CI pipeline to make sure there are some representative examples that are up-to-date.

I'll keep this issue updated on these points.

**Comment by rtkaratekid** [comment]
I understand. Are you planning to have v1.0 come out in those few weeks? I'm interested in XDP for sure, but probably more interested in tracepoints and kprobes (potentially uprobes as well).

I'm happy to keep sifting through the code. Like I've mentioned, I've got a background with bpf, but not rust. I'd be happy to help out with any doc issues if I find them confusing as you come out with stuff as well. Right now I've gotten to the point where I'm poking through how to communicate between the kernel and userspace (i.e. using bpf data structures), how the plumbing with loading the elf files works, and some of the small idiosyncrasies (e.g. naming a kprobe macro ```#[kprobe("__x64_sys_clone")]``` instead of just ```#[kprobe("sys_clone")]```).

To be clear, Ingraind is also really cool, but I'm looking more for the low-level functionality that RedBPF has. GoBPF is also interesting, but gosh darn it! I don't want garbage collection or other dependencies! This just seems like a perfect fit for rust. So I'm happy to do what I can to help out.

**Comment by rtkaratekid** [comment]
@rsdy don't know if you want to keep this issue updated (since there's another issue opened about the API). I thought I'd stop in and ask about API updates. If you don't want to continue to use this issue to do updates, feel free to close it.

**Comment by rsdy** [comment]
Hey!

So we've made a few passes improving the APIs, and added [`redbpf-tools`](https://github.com/redsift/redbpf/tree/master/redbpf-tools) to serve as representative examples of using `redbpf` in a real app. These are always built against the latest version in CI, so you can be sure they work.

I'll fix up the doc tests (as much as possible) today and make a new release.
Thanks for the enthusiasm, this is really helping a lot in finding the biggest pain points. If you have any further questions, feel free to open a new issue.

**Comment by rtkaratekid** [comment]
@rsdy thanks for the update! I'll start poking around in the code again today or tomorrow and either make pull requests or open issues if I find anything.
