### ISSUE TITLE
Ubuntu 18.04 apt

### ISSUE THREAD

**Issue by MarkSwanson** [redsift/redbpf#51]
Hopefully helpful to someone:

sudo apt-get install zlib1g-dev
sudo apt install llvm-9
sudo apt install clang-9
sudo apt install build-essential xz-utils curl

**Comment by rsdy** [comment]
Thanks, I've [updated the readme](https://github.com/redsift/redbpf/commit/7389d4ec3144935857d47c383d48f8dc8907fe8a) with the packages we use in the [CI config](https://github.com/redsift/redbpf/blob/master/.circleci/config.yml#L26)
