### ISSUE TITLE
Does "load" only support xdp programs?

### ISSUE THREAD

**Issue by rtkaratekid** [redsift/redbpf#55]
Looking through the API revamp, it looks really nice! There are still a few plumbing things I don't quite understand yet, but I'm sure they're there for a reason.

Submitted a pull request fixing the example kprobe program given by calling ```cargo bpf add``` and went to load the program in the kernel with ```cargo bpf load``` but realized that it only supports XDP programs? Any thoughts on expanding that functionality?

It's not a big issue (imho) because it's more useful to be able to load programs from a userspace process, but it might be nice for checking the validity of code against the BPF verifier. 

If that's not on the horizon, I'm considering rewriting as many of the BCC tools with this library as I can, I may make a generic "loader" tool that loads and maybe reads from a perf buffer or something. Thoughts?

**Comment by rsdy** [comment]
Yeah, unfortunately the way the kernel treats syscall symbols is a bit special. You'll have to use the "entry point" names as can be found at https://filippo.io/linux-syscall-table/, prefixed by `__x64_` for amd64 architecture. [ingraind](https://github.com/redsift/ingraind/blob/master/src/grains/syscalls.rs#L22) handles this with an architecture-dependent constant.

**Comment by rtkaratekid** [comment]
@alessandrod and @rsdy thanks for the quick replies!

To be clear:
1) you must use architecture specifications in order to access syscall symbols, but not regular kernel functions? Or is this true for all krpobes listed with ```# bpftrace -l | grep kprobe```?

2) In order to load a bpf program to the kernel, you must first ```load()``` and then ```attach_probe()```?

Hopefully this is more helpful than annoying!

**Comment by rsdy** [comment]
Correct on both points.
