### ISSUE TITLE
Out of date `cargo_bpf` example

### ISSUE THREAD

**Issue by jbpratt78** [redsift/redbpf#59]
Hi @rsdy ,

As per your comment [here](https://github.com/redsift/redbpf/issues/52#issuecomment-594631818), I wanted to report that the example on https://ingraind.org/api/cargo_bpf/ seems to be out of date. [Here](https://ingraind.org/api/redbpf_probes/index.html) and [here](https://ingraind.org/api/redbpf_probes/xdp/index.html#example) seem to be the current/correct implementation.

Thank you

**Comment by rsdy** [comment]
Thanks for reporting. Fixed in https://github.com/redsift/redbpf/commit/f2290bd6cfdeea36a21f5d4fb8ef5a52da383fdd
