### ISSUE TITLE
cargo bpf build block_http error: could not compile `redbpf-probes`.

### ISSUE THREAD

**Issue by juaby** [redsift/redbpf#6]
Centos7 3.10.0-1062.4.1.el7.x86_64
rust 1.39
clang version 9.0.0 (tags/RELEASE_900/final)

cargo bpf build block_http
   Compiling redbpf-probes v0.9.6
error[E0588]: packed type cannot transitively contain a `[repr(align)]` type
   --> /home/alphapo/rust/hello-bpf/target/release/build/redbpf-probes-fcf682ba7259472e/out/gen_helpers.rs:977:1
    |
977 | / pub struct desc_struct {
978 | |     pub __bindgen_anon_1: desc_struct__bindgen_ty_1,
979 | | }
    | |_^

error[E0587]: type has conflicting packed and align representation hints
    --> /home/alphapo/rust/hello-bpf/target/release/build/redbpf-probes-fcf682ba7259472e/out/gen_helpers.rs:5432:1
     |
5432 | / pub struct xsave_struct {
5433 | |     pub i387: i387_fxsave_struct,
5434 | |     pub xsave_hdr: xsave_hdr_struct,
5435 | |     pub ymmh: ymmh_struct,
...    |
5439 | |     pub __bindgen_padding_0: [u8; 48usize],
5440 | | }
     | |_^

error: aborting due to 2 previous errors

error: could not compile `redbpf-probes`.

To learn more, run the command again with --verbose.
error: failed to compile the `block_http' program

**Comment by juaby** [comment]
packed type  and [repr(align)] type is incomp.....

**Comment by juaby** [comment]
cargo bpf build block_http
   Compiling hello-bpf v0.1.0 (/home/alphapo/rust/hello-bpf)
error: unexpected end of input, expected expression
  --> src/block_http/main.rs:36:1
   |
36 | #[xdp]
   | ^^^^^^

**Comment by alessandrod** [comment]
Hi, thanks for reporting the issue!

Is 3.10.0-1062.4.1.el7.x86_64 the kernel version you're trying to target? I think BPF was first introduced in 3.18, and 4.15 is the earliest version redbpf supports.

That said we should fail with a better error.

**Comment by juaby** [comment]
thanks

**Comment by juaby** [comment]
CentOS Linux release 8.0.1905 (Core)
Linux po.com 4.18.0-80.11.2.el8_0.x86_64 #1 SMP Tue Sep 24 11:32:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
rustc 1.39.0 (4560ea788 2019-11-04)

cargo bpf build block_http

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/lib.rs:2:1
  |
2 | #![feature(const_fn, const_transmute)]


error: unexpected end of input, expected expression
  --> src/block_http/main.rs:43:1
   |
43 | #[xdp]

**Comment by alessandrod** [comment]
Thanks for the report. I just created a PR with the fix https://github.com/redsift/redbpf/pull/10

**Comment by gmilleramilar** [comment]
The second part of the message by @juaby above is still an issue AFAICT.  I still get an "unexpected end of input" error.  Should a new issue be opened for that?

**Comment by alessandrod** [comment]
Ah, you're right! I'm working on a fix no need to open another issue.

**Comment by p2mate** [comment]
> The second part of the message by @juaby above is still an issue AFAICT. I still get an "unexpected end of input" error. Should a new issue be opened for that?

I got it to work by replacing [#xdp] with [#xdp("http_block")]. The actual string doesn't seem to matter much but it does show up as the name of the program when listing all loaded ebpf programs for example.

**Comment by alessandrod** [comment]
@p2mate yup that was the problem. It's now fixed by https://github.com/redsift/redbpf/pull/12

**Comment by juaby** [comment]
@alessandrod test pass, ths

**Comment by rsdy** [comment]
I've merged #12, so this should be solved, too. Please re-open if there are any more issues here.
