### ISSUE TITLE
cargo build failure

### ISSUE THREAD

**Issue by rhdxmr** [redsift/redbpf#61]
running 'cargo build' incurs this error and fails.

> warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred
   --> cargo-bpf/src/main.rs:152:29
    |
152 |                     .author(crate_authors!("\n"))
    |                             ^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default
    = note: this warning originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

> warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred
   --> cargo-bpf/src/main.rs:152:29
    |
152 |                     .author(crate_authors!("\n"))
    |                             ^^^^^^^^^^^^^^^^^^^^
    |
    = note: this warning originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

>   Compiling redbpf-tools v0.1.0 (/home/esrse/opensource/redbpf/redbpf-tools)
error: failed to run custom build command for `redbpf-tools v0.1.0 (/home/esrse/opensource/redbpf/redbpf-tools)`

> Caused by:
  process didn't exit successfully: `/home/esrse/opensource/redbpf/target/debug/build/redbpf-tools-2917edd5a3498c8f/build-script-build` (exit code: 101)
--- stdout
IR processed before: "/home/esrse/opensource/redbpf/target/debug/build/redbpf-tools-7d419f2e7a1f3ba0/out/target/bpf/programs/iotop/iotop-e206c2d5c99cdaa7.bc", after: "/home/esrse/opensource/redbpf/target/debug/build/redbpf-tools-7d419f2e7a1f3ba0/out/target/bpf/programs/iotop/iotop-e206c2d5c99cdaa7.bc.proc"

> --- stderr
   Compiling probes v0.1.0 (/home/esrse/opensource/redbpf/redbpf-tools/probes)
warning: due to multiple output types requested, the explicitly specified output file name will be adapted for each output type

> warning: ignoring --out-dir flag due to -o flag

>    Finished release [optimized] target(s) in 0.51s
thread 'main' panicked at 'couldn't compile probes: NoOPT', redbpf-tools/build.rs:11:5
stack backtrace:
   0:     0x55ea1d1a8544 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55ea1d1a8544 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55ea1d1a8544 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x55ea1d1a8544 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55ea1d1caaec - core::fmt::write::h4e6a29ee6319c9fd
                               at src/libcore/fmt/mod.rs:1052
   5:     0x55ea1d1a5157 - std::io::Write::write_fmt::hf06b1c86d898d7d6
                               at src/libstd/io/mod.rs:1426
   6:     0x55ea1d1aabd5 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55ea1d1aabd5 - std::sys_common::backtrace::print::hcc4377f1f882322e
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55ea1d1aabd5 - std::panicking::default_hook::{{closure}}::hc172eff6f35b7f39
                               at src/libstd/panicking.rs:204
   9:     0x55ea1d1aa8c1 - std::panicking::default_hook::h7a68887d113f8029
                               at src/libstd/panicking.rs:224
  10:     0x55ea1d1ab18a - std::panicking::rust_panic_with_hook::hb7ad5693188bdb00
                               at src/libstd/panicking.rs:472
  11:     0x55ea1d1aad70 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  12:     0x55ea1d1c9601 - core::panicking::panic_fmt::hb1f3e14b86a3520c
                               at src/libcore/panicking.rs:85
  13:     0x55ea1d1c9423 - core::option::expect_none_failed::he6711468044f7162
                               at src/libcore/option.rs:1199
  14:     0x55ea1be9b48d - core::result::Result<T,E>::expect::hbbd26b4bc15af957
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/result.rs:991
  15:     0x55ea1be9b006 - build_script_build::main::hed45ef7a00890b0b
                               at redbpf-tools/build.rs:11
  16:     0x55ea1be9b540 - std::rt::lang_start::{{closure}}::h59d69fa85d45147c
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  17:     0x55ea1d1aaca3 - std::rt::lang_start_internal::{{closure}}::hb26e39676675046f
                               at src/libstd/rt.rs:52
  18:     0x55ea1d1aaca3 - std::panicking::try::do_call::he4701ab6e48d80c0
                               at src/libstd/panicking.rs:305
  19:     0x55ea1d1b1f27 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  20:     0x55ea1d1ab630 - std::panicking::try::hd3de25f3cb7024b8
                               at src/libstd/panicking.rs:281
  21:     0x55ea1d1ab630 - std::panic::catch_unwind::h86c02743a24e3d92
                               at src/libstd/panic.rs:394
  22:     0x55ea1d1ab630 - std::rt::lang_start_internal::h9cf8802361ad86c2
                               at src/libstd/rt.rs:51
  23:     0x55ea1be9b519 - std::rt::lang_start::h98423b3d225ed880
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  24:     0x55ea1be9b18a - main
  25:     0x7f05dc628b97 - __libc_start_main
  26:     0x55ea1be9a7fa - _start
  27:                0x0 - <unknown>

**Comment by alessandrod** [comment]
The error could be improved, but it means you're missing the opt tool from llvm, see https://releases.llvm.org/1.0/docs/CommandGuide/opt.html

The binary is installed as part of the `llvm` package in ubuntu I think, not sure about other distros.

**Comment by rhdxmr** [comment]
In command line I can find opt executable. I built llvm using llvmenv. So opt is not at the system path. Is it the reason of problem?

> redbpf on  master via 🦀 v1.42.0 
01:16:30 12 ❯  which opt
/home/esrse/.local/share/llvmenv/llvm-mirror/bin/opt
redbpf on  master via 🦀 v1.42.0 
01:16:32 12 ❯  opt --version
LLVM (http://llvm.org/):
  LLVM version 10.0.0svn
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: skylake

**Comment by rhdxmr** [comment]
I just got to know that LLVM version 9 is required for redbpf. But mine is 10 😅
I found it by reading source code but it is explictly mentioned at README file.
I should've read it carefully.
Thank you
