### ISSUE TITLE
Can't install with Amazon Linux 2 due to LLVM issue

### ISSUE THREAD

**Issue by mhausenblas** [redsift/redbpf#89]
I tried to set up a development env in Docker with RedBPF, using:

```
FROM amazonlinux:2
RUN curl https://sh.rustup.rs -sSf | \
        sh -s -- -y --default-toolchain stable && \
        PATH="/root/.cargo/bin:$PATH" rustup install stable
RUN yum -y install clang-10.0.0 \
    llvm-10.0.0 \
    llvm-libs-10.0.0 \
    llvm-devel-10.0.0 \
    llvm-static-10.0.0 \
    kernel \
    kernel-devel \
    elfutils-libelf-devel \
    ca-certificates 
RUN PATH="/root/.cargo/bin:$PATH" cargo install cargo-bpf
ENV PATH $PATH:/root/.cargo/bin
WORKDIR /tmp
```

When I do a `docker build` this fails with:

```
...
error: No suitable version of LLVM was found system-wide or pointed
       to by LLVM_SYS_100_PREFIX.

       Consider using `llvmenv` to compile an appropriate copy of LLVM, and
       refer to the llvm-sys documentation for more information.

       llvm-sys: https://crates.io/crates/llvm-sys
       llvmenv: https://crates.io/crates/llvmenv
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/llvm-sys-100.2.0/src/lib.rs:483:1
    |
483 | / std::compile_error!(concat!(
484 | |       "No suitable version of LLVM was found system-wide or pointed
485 | |        to by LLVM_SYS_", env!("CARGO_PKG_VERSION_MAJOR"), "_PREFIX.
486 | |
...   |
490 | |        llvm-sys: https://crates.io/crates/llvm-sys
491 | |        llvmenv: https://crates.io/crates/llvmenv"));
    | |____________________________________________________^

error: aborting due to previous error

error: could not compile `llvm-sys`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-bpf v1.1.2`, intermediate artifacts can be found at `/tmp/cargo-installKGJVzw`
```

Any idea what I'm doing wrong? I thought I got all the deps? 8-}

Great project, BTW!

**Comment by alessandrod** [comment]
Could you try setting `LLVM_SYS_100_PREFIX=/usr`?

**Comment by mhausenblas** [comment]
Thanks a lot for your speedy reply @alessandrod and we have a new error (progress, I suppose? :)

```
error: failed to run custom build command for `llvm-sys v100.2.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installBkCtpS/release/build/llvm-sys-e44a5f3399cb748a/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=LLVM_SYS_100_PREFIX
  cargo:rerun-if-env-changed=LLVM_SYS_100_IGNORE_BLACKLIST
  cargo:rerun-if-env-changed=LLVM_SYS_100_STRICT_VERSIONING
  cargo:rerun-if-env-changed=LLVM_SYS_100_NO_CLEAN_CFLAGS
  cargo:rerun-if-env-changed=LLVM_SYS_100_USE_DEBUG_MSVCRT
  cargo:rerun-if-env-changed=LLVM_SYS_100_FFI_WORKAROUND
  Didn't find usable system-wide LLVM.

  --- stderr
  thread 'main' panicked at 'Failed to execute "/usr/bin/llvm-config": Os { code: 2, kind: NotFound, message: "No such file or directory" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/llvm-sys-100.2.0/build.rs:84:22
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by alessandrod** [comment]
This is a bug in `llvm-sys` `build.rs` I ran into a while ago. What's the output of `which llvm-config` and `which llvm-config-10`?

**Comment by alessandrod** [comment]
Also what's the output of `rpm -q --whatprovides /usr/bin/llvm-config`?

**Comment by mhausenblas** [comment]
```
bash-4.2# which llvm-config
which: no llvm-config in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.cargo/bin)
bash-4.2# which llvm-config-10
which: no llvm-config-10 in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.cargo/bin)
bash-4.2# rpm -q --whatprovides /usr/bin/llvm-config
error: file /usr/bin/llvm-config: No such file or directory
```
Hmmm …

**Comment by alessandrod** [comment]
Did `yum install llvm-devel-10.0.0` actually succeed?

**Comment by mhausenblas** [comment]
Aha! You're right!

```
Step 3/5 : RUN yum -y install clang-10.0.0     llvm-10.0.0     llvm-libs-10.0.0     llvm-devel-10.0.0     llvm-static-10.0.0     kernel     kernel-devel     elfutils-libelf-devel     ca-certificates
 ---> Running in cef18a968bf7
Loaded plugins: ovl, priorities
No package clang-10.0.0 available.
No package llvm-10.0.0 available.
No package llvm-libs-10.0.0 available.
No package llvm-devel-10.0.0 available.
No package llvm-static-10.0.0 available.
```

Wondering where I could get that from, for AL2 :/

**Comment by rsdy** [comment]
The trick we use is to overcome this is to create a static build FOR AL2, but ON Fedora. The [Dockerfile](https://github.com/redsift/ingraind-build/blob/master/Dockerfile.fedora) documenting this is here.

Then you can [follow the steps](https://github.com/redsift/ingraind/blob/master/.circleci/config.yml#L265) in the ingraind build file to download and build your app for the correct kernel version. The resulting binary that targets must will work just perfectly on AL2.

Unfortunately until RHEL & derivatives upgrade to latest and greatest, I don't see this changing, and LLVM 11 is also just around the corner.

**Comment by mhausenblas** [comment]
That worked, thank you so much @rsdy and also for your support @alessandrod!

**Comment by chadbrewbaker** [comment]
Can't the llvm RPMs be installed on AmazonLinux 2?

**Comment by rsdy** [comment]
@chadbrewbaker as far as i'm aware, there are no official llvm 11 rpms for amazon linux 2. If you can find them, or try to adapt the ones from Fedora Rawhide, they might work.

**Comment by chadbrewbaker** [comment]
Ideally rustup would could compile clang alongside llvm so there is nightly support for all these distros. Doubt we will see good back ports.

**Comment by rsdy** [comment]
@chadbrewbaker I think the most practical thing is still to build static binaries targeting the right kernel using another distro as compilation host.

**Comment by chanansh** [comment]
cannot install postgress13-devel due to this problem
```
Error: Package: postgresql13-devel-13.6-1PGDG.rhel7.x86_64 (pgdg13)
           Requires: llvm-toolset-7-clang >= 4.0.1
```

could not find a way to update llvm-toolset-7-clang

**Comment by rsdy** [comment]
You won't be able to build RedBPF on Amazon Linux at all. Use another distribution to cross-compile for the right kernel. There are no plans for supporting builds on Amazon Linux or other non-Fedora RedHat derivatives directly, as they are just prohibitively an unapologetically out of date.

**Comment by gfiocco** [comment]
I was able to install llvm-toolset-7-clang in Amazon Linux 2 (ami-01bb5fb90f6e8dc9d) with the following:

> `sudo yum -y install http://mirror.centos.org/centos/7/extras/x86_64/Packages/centos-release-scl-rh-2-3.el7.centos.noarch.rpm`

> `sudo yum -y install http://mirror.centos.org/centos/7/extras/x86_64/Packages/centos-release-scl-2-3.el7.centos.noarch.rpm`

> `sudo yum -y install http://mirror.centos.org/centos/7/sclo/x86_64/rh/Packages/l/llvm-toolset-7-clang-4.0.1-1.el7.x86_64.rpm`

**Comment by FrankDupree** [comment]
@gfiocco boy are you a life saver, i would have never thought to see the answer here. you just saved me some postgis installation headaches. thanks!
